default: &default
  adapter: postgresql
  # adapter: jdbc
  # database: splicedb
  # username: splice
  # password: admin
  # driver: com.splicemachine.db.jdbc.ClientDriver
  # url: jdbc:splice://localhost:1527/splicedb
  # prepared_statements: true
  # pool: 1000


development:
  <<: *default
  database: jruby_splice_development

test:
  <<: *default
  database: jruby_splice_test

production:
  <<: *default
  database: jruby_splice_production
