default: &default
  # Used only for presentation on Heroku.
  # Delete database.yml, and rename database_example.yml to database.yml
  adapter: postgresql

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
